import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer } from '../components/Footer'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import React, { useEffect, useState } from 'react';
import { fetchAddToCart, fetchMinusFromCart, fetchRemoveFromCart, loadCart } from '../redux/cart/action';
import { useAppSelector, useAppDispatch } from '../store';
import { LoadingState } from '../models'
import { loadOneProduct } from '../redux/product/action'
import Skeleton from 'react-loading-skeleton'
import { Container } from '@mui/material'
import home from '../styles/Index.module.css'
import cart from '../styles/Cart.module.css'
import CartItem from '../components/CartItem'
import Link from 'next/link'
import { PrintDisabled } from '@mui/icons-material'
import { useRouter } from 'next/router'


interface CartItems {
	id: number,
	product: string,
	color: string,
	size: string,
	icon: string,
	number: number,
	product_price: number,
	tc_number: number | string,
	tc_price: number
}



const Cart: NextPage = () => {

	const cartLoaded = useAppSelector(state => state.cart.loading)
	const carts = useAppSelector(state => state.cart.products)
	// const cartCount = useAppSelector(state => state.cart.productDetailIds)
	
	const [totalPrice, setGetTotalPrice] = useState(0)
	const dispatch = useAppDispatch()


	useEffect(() => {
		dispatch(loadCart())
		
		JSON.parse(localStorage.getItem('cartItems')!)

	}, [totalPrice])
	
	useEffect(() => {
		dispatch(loadCart())
		getTotalPrice()
	}, [])
	
	function getTotalPrice() {
		let carts:CartItems[]= JSON.parse(localStorage.getItem('cartItems')!)
		
		let total = carts.map((item) => 
		Number(item.product_price) * Number(item.tc_number))
		.reduce((a, b) => a + b, 0)
		
		setGetTotalPrice(total)
	}
	


	const router = useRouter()

	return (

		<>
			<Heading />
			<Navbar />
			<Head>
				<title>Cart</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<>
				{/* {console.log('carts:', carts)} */}
				{/* {console.log('cartLoaded:',cartLoaded ,)} */}
			</>
			<div className={cart.pageBox}>
				<Container>
					<div>
						<h1 className={cart.Title}>Cart</h1>
						<span className={cart.page}>Home. Pages.</span>
						<span className={cart.nowPage}>
							Cart
						</span>
					</div>
				</Container>
			</div>
			<Container>
				<div className={cart.box}>
					<div>
						{cartLoaded !== LoadingState.Loaded ?
							<Skeleton /> :
							carts.length > 0 ? carts.map(productInCart =>


								<CartItem
									key={productInCart.id}
									product={productInCart.product}
									icon={productInCart.icon}
									color={productInCart.color}
									size={productInCart.size}
									tc_number={productInCart.tc_number}
									tc_price={productInCart.tc_price}

					
									onMinusFromCart={() =>  {dispatch(fetchMinusFromCart(productInCart.id)) ;getTotalPrice()}}
									onRemoveFromCart={() => dispatch(fetchRemoveFromCart(productInCart.id))}
									onAddToCart={() => {dispatch(fetchAddToCart(productInCart.id)) ;getTotalPrice()}}

								/>

							)
								: <div className={cart.empty}>Cart is empty</div>
						}
					</div>
					<form className={cart.totalBox} >
						<div >
							<div>Total</div>
							<div className={cart.totalPrice}>{totalPrice}</div>
						</div>
						<button>Proceed To Checkout</button>

					</form>

				</div>

			</Container>
			<Footer />
		</>
	)
}


export default Cart