import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import Link from 'next/link'
import { Footer } from '../components/Footer'
import { Container } from '@mui/system'
import { useState } from 'react'
import { useForm, SubmitHandler } from 'react-hook-form'
import { useRouter } from 'next/router'
import create from '../styles/CreateProduct.module.css'
import { LineAxisOutlined } from '@mui/icons-material'
import axios from 'axios'
import { dataSlider } from '../components/DataSlider'
import { AddProduct } from '../components/AddNewProduct'
import { AddColumn } from '../components/AddColumn'


type Inputs = {
	name: String
	description: String
}

const CreateProduct: NextPage = () => {


	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Heading />
			<Navbar />

<div className={create.box}>
<div className={create.div}>
			<AddProduct/>
			</div>

			<div className={create.div}>
			<AddColumn/>
			</div>
			</div>


			<Footer />
		</div>
	)
}

export default CreateProduct
