import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import error from '../styles/Invoice.module.css'
import Link from 'next/link'
import errorPhoto from '../pages/photo/error.png'
import { Footer } from '../components/Footer'
import errorImage from './error.png'
import { Container } from '@mui/system'
import { useEffect, useState } from 'react'
import {Invoice} from '../components/Receipt'


interface Props{
    id:number
    invoiceNumber:string
    status_id:string
    user_id:string
    address_id:string
    totalPrice:number
    product:string
    icon: string
    color:string
    size:string
    number:number

}





const InvoicePage: NextPage = () => {

    const [invoices, setInvoice] = useState<Props[]>([])

	async function fetchInvoice() {
		let res = await fetch(`${process.env.NEXT_PUBLIC_ANALYTICS_ID}/invoice`,{
            method: 'GET',
            headers: {
                'Authorization': `Bearer ${localStorage.getItem('token')}`
                
            }
        }
   )
		
		let invoice = (await res.json()).invoiceRecord
		setInvoice(invoice)
	}{}

	useEffect(()=>{
		fetchInvoice()
	},[setInvoice])

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Heading />
			<Navbar />
            {invoices.map((invoices) => (
			<Invoice
                    id={invoices.id}
                    invoiceNumber={invoices.invoiceNumber}
                    status_id={invoices.status_id}
                    user_id={invoices.user_id}
                    address_id={invoices.address_id}
                    totalPrice={invoices.totalPrice} product={''} icon={''} color={''} size={''} number={0}		
			/>
			))}



			<Footer />
		</div>
	)
}

export default InvoicePage
