import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Footer } from '../components/Footer'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import loginStyles from '../styles/Login.module.css'

const Register: NextPage = () => {
  return (
    <div>
      <Heading/>
      <Navbar/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className={loginStyles.loginBox} >
      <form className={loginStyles.loginForm}  action="/send-data-here" method="post">
        <div className={loginStyles.loginWork}>Register</div>
        <div className={loginStyles.loginCommet}>
        Create your Account
					</div>
  <input className={loginStyles.textBox} type="text" id="name" placeholder="Username" />
  <input className={loginStyles.textBox} type="text" id="email" placeholder="EmailAddress" />
  <input className={loginStyles.textBox} type="text" id="Password" placeholder="Password" />
  <input className={loginStyles.inputFile} type="file" id="Icon" value="asd" />
  <button className={loginStyles.button} type="submit">Register</button>
<Link href="/login"><p className={loginStyles.regiseterCommet}>Have Account ? Sign in account</p></Link>
  </form>
  </div>
  <Footer/>
    </div>
    
  )
}

export default Register
