import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import error from '../styles/Error.module.css'
import Link from 'next/link'
import errorPhoto from '../pages/error.png'
import { Footer } from '../components/Footer'

const Error: NextPage = () => {
	return (
		<div >
			<Heading />
			<Navbar />

			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={error.container}>
				<Image
					className={error.photo}
					src={errorPhoto}
					width={1000}
					height={600}
				/>
				<Link href='/Home'>
					<p className={error.button}>Home Page</p>
				</Link>
			</div>

			<Footer/>
		</div>
	)
}

export default Error
