import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import error from '../styles/Error.module.css'
import Link from 'next/link'

const Error: NextPage = () => {
	return (
		<div >
			<Heading />
			<Navbar />

			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={error.container}>
				<Image
					className={error.photo}
					src='/error.png'
					width={500}
					height={500}
				/>
				<Link href='/login'>
					<p className={error.button}>Home Page</p>
				</Link>
			</div>
		</div>
	)
}

export default Error
