import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Footer } from '../components/Footer'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import { ProductCard } from '../components/ProductCard'
import styles from '../styles/Home.module.css'
import { Container } from '@mui/material'

const Home: NextPage = () => {
	const products = [
		{
			id: 1,
			name: 'bag',
			image: 'https://media.gucci.com/style/DarkGray_Center_0_0_1200x1200/1658940346/631685_2KQGG_8375_001_100_0000_Light-Ophidia-GG-medium-tote.jpg',
			color: 'red',
			code: 'af123',
			price: 100
		},
		{
			id: 2,
			name: 'car',
			image: 'https://media.gucci.com/style/DarkGray_Center_0_0_1200x1200/1658940346/631685_2KQGG_8375_001_100_0000_Light-Ophidia-GG-medium-tote.jpg',
			color: 'blue',
			code: 'af133',
			price: 120
		},
		{
			id: 3,
			name: 'table',
			image: 'https://media.gucci.com/style/DarkGray_Center_0_0_1200x1200/1658940346/631685_2KQGG_8375_001_100_0000_Light-Ophidia-GG-medium-tote.jpg',
			color: 'black',
			code: 'af122',
			price: 130
		},

		{
			id: 4,
			name: 'table',
			image: 'https://media.gucci.com/style/DarkGray_Center_0_0_1200x1200/1658940346/631685_2KQGG_8375_001_100_0000_Light-Ophidia-GG-medium-tote.jpg',
			color: 'black',
			code: 'af122',
			price: 130
		}
	]

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Heading />
			<Navbar />
<Container>
			<div className={styles.productcard}>
				{products.map((product) => (
					<ProductCard
						key={product.id}
						name={product.name}
						image={product.image}
						color={product.color}
						code={product.code}
						price={product.price}
					/>
				))}
			</div>
      </Container>
			<Footer />
		</div>
	)
}

export default Home
