import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Heading } from '../components/Heading'
import { Navbar } from '../components/Navbar'
import loginStyles from '../styles/Login.module.css'

const login: NextPage = () => {
  return (
    <div >
      <Heading/>
      <Navbar/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className={loginStyles.loginBox} >
      <form className={loginStyles.loginForm}  action="/send-data-here" method="post">
        <div className={loginStyles.loginWork}>Login</div>
        <div className={loginStyles.loginCommet}>Please login using account detail bellow.</div>
  <input className={loginStyles.textBox} type="text" id="first" name="first" placeholder="Email Address" />
  <input className={loginStyles.textBox} type="text" id="last" name="last" placeholder="Password" />
  <button className={loginStyles.button} type="submit">Sign In</button>
<Link href="/"><p className={loginStyles.loginCommet}>Don't have Account ? Create account</p></Link>
  </form>
  </div>

    </div>
  )
}

export default login
